name: Zone Lafrance
favicon: null
layout_spectrum: 0.20016294275410473
typography_spectrum: 0.8641910108271986
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.24783900612965226
  lightness: 0.6712886355817318
  saturation: 0.2449077602941543
  rhythmicContrast: 0.7959443349391222
purpose: []
